url: ''
baseurl: ''

# Site settings
title: Chaitanya
email: chaitanya.suvarna.dev@gmail.com
description: "I am Chaitanya Suvarna. This is a portfolio site I created for myself using Jekyll theme."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/chaitanya-suvarna/
  - title: github
    url: https://github.com/chaitanya-suvarna
  - title: twitter
    url: https://twitter.com/chaitanyadev_
  - title: wordpress
    url: http://chaitanyasuvarna.wordpress.com/
  - title: envelope
    url: mailto:chaitanya.suvarna.dev@gmail.com


# Build settings
markdown: kramdown
permalink: pretty
