url: ''
baseurl: ''

# Site settings
title: Chaitanya
email: chaitanya.suvarna.dev@gmail.com
description: "I am Chaitanya Suvarna. This is a portfolio site I created for myself using Jekyll theme."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/chaitanya-suvarna/
  - title: github
    url: https://github.com/chaitanya-suvarna
  - title: twitter
    url: https://twitter.com/chaitanyadev_
  - title: wordpress
    url: http://chaitanyasuvarna.wordpress.com/
  - title: envelope
    url: mailto:chaitanya.suvarna.dev@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
